"use client";

import Link from "next/link";
import { useState } from "react";
import { ArrowLeft, Check, Download, Printer } from "lucide-react";
import { Brand } from "@/components/brand";
import { demoCriteria, demoMilestone, money } from "@/lib/demo";

export function ApprovalReceipt() {
  const [toast, setToast] = useState("");
  const download = () => {
    window.print();
    setToast("Print dialog opened — choose Save as PDF");
    window.setTimeout(() => setToast(""), 2800);
  };
  return (
    <main className="receipt-shell">
      <div className="receipt-toolbar"><Brand /><div className="receipt-toolbar__actions"><Link className="button button--small button--outline" href="/workspace"><ArrowLeft size={13} /> Workspace</Link><button className="button button--small button--ink" onClick={download}><Download size={13} /> Save PDF</button></div></div>
      <article className="receipt-page" aria-label="Milestone approval record">
        <header className="receipt-head"><div><Brand /><h1>Milestone approval record</h1></div><div className="receipt-stamp"><span><Check size={23} strokeWidth={3} /><br />APPROVED<br />JUL 19 2026</span></div></header>
        <div className="receipt-facts"><div><span>Agency</span><strong>{demoMilestone.agency}</strong></div><div><span>Client</span><strong>{demoMilestone.client}</strong></div><div><span>Milestone value</span><strong>{money.format(demoMilestone.amountMinor / 100)} USD</strong></div></div>
        <span className="receipt-section-title">Approved scope · SOW revision 3</span>
        <section className="receipt-criteria">
          {demoCriteria.map((item) => <div className="receipt-criterion" key={item.id}><span className="criterion-id">{item.id}</span><div><strong>{item.title}</strong><small>{item.result.observedRc2}</small></div><span className="status-badge status-badge--pass"><Check size={10} /> Passed</span></div>)}
        </section>
        <section className="receipt-approval"><div><span className="receipt-section-title">Client decision</span><h3>Approved for invoicing</h3><p>Mara Chen · Acme Outdoors · Jul 19, 2026 at 10:18 PM PDT</p></div><div className="receipt-sign">Mara Chen</div></section>
        <section className="hash-block"><div><span className="receipt-section-title">Evidence snapshot</span><p>run_2048_rc2 · launch-rc2.acme-demo.test<br />Chromium 140 · 6 results · 6 artifacts<br />SHA-256: 9e60753140ac65ebdf…77e419</p></div><div><span className="receipt-section-title">Canonical record</span><p>MP-2048-APR · revision 3 · decision 1<br />Source SHA-256: 3f45b1d8e829a209…a209<br />Receipt SHA-256: d82c71a48fe619ef…19ef</p></div></section>
        <p className="receipt-disclaimer">This record documents acceptance evidence and a client decision for the named project milestone. It is not an invoice, payment guarantee, legal e-signature, or certification of Web Content Accessibility Guidelines compliance. Evidence reflects the specified staging build at the recorded time.</p>
        <footer className="receipt-page__foot"><span>Generated by MilestoneProof</span><span>Verify record · milestoneproof.app/v/MP-2048-APR</span><span>Page 1 of 1</span></footer>
      </article>
      {toast && <div className="toast" role="status"><Printer size={16} color="var(--lime)" /> {toast}</div>}
    </main>
  );
}

