"use client";

import { useCallback, useEffect, useState } from "react";
import { AlertTriangle, CheckCircle2, FileWarning, LoaderCircle, RefreshCw } from "lucide-react";
import { Brand } from "@/components/brand";
import { formatTimestamp } from "@/lib/format";
import { OperatorPauseControls } from "@/components/operator-pause-controls";
import { OperatorDemoRequests } from "@/components/operator-demo-requests";
import { clientRequestMessage, fetchWithTimeout } from "@/lib/client-request";
import { operatorInvitePresentation, type BetaInviteStatus } from "@/lib/operator-invite-state";

type Feedback = { id: string; public_id: string; email?: string | null; category: string; message: string; page_path: string; status: string; created_at: string };
type PrivacyRecord = { id: string; public_id: string; agency_name: string; client_name: string; project_name: string; milestone_title: string; status: string; legal_hold: boolean; retention_until: string; privacy_deletion_requested_at?: string | null; deletion_status: string };
type Privacy = { id: string; public_id: string; request_type: string; email: string; details?: string | null; status: string; assigned_to?: string | null; internal_notes?: string | null; identity_verified_at?: string | null; response_summary?: string | null; response_sent_at?: string | null; matchedRecords: PrivacyRecord[]; activeHolds?: Array<{ id: string; record_id: string; reason: string; owner_email: string; review_at: string }>; created_at: string };
type Job = { id: string; record_id: string; status: string; build_label: string; target_origin: string; last_error?: string | null; acknowledged_at?: string | null; created_at: string };
type InvoiceJob = { id: string; record_id: string; status: string; attempts: number; last_error?: string | null; claimed_at?: string | null; created_at: string; updated_at: string };
type Notification = { id: string; event_type: string; title: string; delivery_status: string; delivery_error?: string | null; delivery_attempts?: number; created_at: string };
type DeletionFailure = { id: string; public_id: string; project_name: string; deletion_status: string; deletion_error?: string | null; deletion_requested_at: string };
type AccountDeletionFailure = { id: string; email: string; status: string; attempts: number; last_error?: string | null; requested_at: string };
type Maintenance = { id: number; task: string; status: string; started_at: string; completed_at?: string | null; summary?: Record<string, unknown> | null; error?: string | null };
type Invite = { id: string; email: string; status: BetaInviteStatus; adult_sponsor?: string | null; invited_by: string; invited_at: string; removed_at?: string | null; last_sign_in_requested_at?: string | null };
type Item = Record<string, unknown> & { id: string | number; created_at: string };
type Payload = { operator: string; summary: { newFeedback: number; activeJobIssues: number; openPrivacyRequests: number; runsLast24Hours: number }; feedback: Feedback[]; events: Item[]; jobs: Job[]; invoiceJobs: InvoiceJob[]; privacy: Privacy[]; notifications: Notification[]; deletionFailures: DeletionFailure[]; accountDeletionFailures: AccountDeletionFailure[]; maintenance: Maintenance[]; invites: Invite[]; error?: string };

export function OperatorConsole() {
  const [data, setData] = useState<Payload | null>(null);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const [busy, setBusy] = useState("");
  const [privacyDrafts, setPrivacyDrafts] = useState<Record<string, { status: string; assignedTo: string; internalNotes: string; responseSummary: string; responseSent: boolean }>>({});
  const [correctionDrafts, setCorrectionDrafts] = useState<Record<string, { recordId: string; fieldName: "agency_name" | "client_name" | "project_name" | "milestone_title"; correctedValue: string; reason: string }>>({});
  const [inviteEmail, setInviteEmail] = useState("");
  const [responsibleOperator, setResponsibleOperator] = useState("");
  const load = useCallback(async () => {
    setError("");
    try {
      const response = await fetchWithTimeout("/api/admin/overview", { cache: "no-store" }, 20_000);
      const payload = await response.json() as Payload;
      if (!response.ok) throw new Error(payload.error ?? "Operator overview unavailable.");
      setData(payload);
      setPrivacyDrafts(Object.fromEntries(payload.privacy.map((item) => [item.id, { status: item.status, assignedTo: item.assigned_to ?? "", internalNotes: item.internal_notes ?? "", responseSummary: item.response_summary ?? "", responseSent: Boolean(item.response_sent_at) }])));
      setCorrectionDrafts(Object.fromEntries(payload.privacy.map((item) => [item.id, { recordId: item.matchedRecords[0]?.id ?? "", fieldName: "project_name" as const, correctedValue: "", reason: "" }])));
    } catch (cause) { setError(clientRequestMessage(cause, "Operator overview unavailable.")); }
  }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const update = async (key: string, body: Record<string, unknown>): Promise<boolean> => {
    setBusy(key); setError(""); setNotice("");
    try {
      const response = await fetchWithTimeout("/api/admin/overview", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }, 25_000);
      const payload = await response.json() as { error?: string; affected?: number; amendmentId?: string };
      if (!response.ok) throw new Error(payload.error ?? "Operator update failed.");
      if (typeof payload.affected === "number") setNotice(`${payload.affected} matched record${payload.affected === 1 ? "" : "s"} updated.`);
      else if (payload.amendmentId) setNotice("Append-only correction recorded in the transaction audit trail.");
      else setNotice("Operator update recorded.");
      await load();
      return true;
    } catch (cause) {
      setError(clientRequestMessage(cause, "Operator update failed."));
      return false;
    }
    finally { setBusy(""); }
  };
  const refresh = async () => {
    setBusy("refresh");
    await load();
    setBusy("");
  };
  if (!data && !error) return <main className="dashboard-shell"><section className="review-state"><LoaderCircle className="spin" /><h1>Loading beta operations</h1></section></main>;
  if (!data) return <main className="dashboard-shell"><section className="review-state"><FileWarning /><h1>Operator console unavailable</h1><p>{error}</p><button className="button button--outline" onClick={() => void load()}>Retry</button></section></main>;
  return <main className="dashboard-shell"><header className="dashboard-header"><Brand /><div>{data.operator}<button className="button button--small button--outline" disabled={busy === "refresh"} onClick={() => void refresh()}><RefreshCw size={13} /> {busy === "refresh" ? "Refreshing…" : "Refresh"}</button></div></header><div className="dashboard-main"><section className="dashboard-heading"><div><div className="legal-kicker">Private operator console</div><h1>Beta operations</h1><p>Feedback, unresolved jobs, privacy requests, and delivery failures in one view.</p></div></section>{error && <div className="analysis-error" role="alert">{error}</div>}{notice && <div className="analysis-notice" role="status">{notice}</div>}<div className="operator-summary"><div><span>New feedback</span><strong>{data.summary.newFeedback}</strong></div><div><span>Job issues</span><strong>{data.summary.activeJobIssues}</strong></div><div><span>Privacy queue</span><strong>{data.summary.openPrivacyRequests}</strong></div><div><span>Runs / 24h</span><strong>{data.summary.runsLast24Hours}</strong></div></div><OperatorPauseControls /><OperatorDemoRequests />
    <section className="panel operator-section"><h2>Beta invitations</h2><div className="operator-invite-form"><label>Business email<input type="email" value={inviteEmail} onChange={(event) => setInviteEmail(event.target.value)} placeholder="tester@agency.com" /></label><label>Responsible operator<input value={responsibleOperator} onChange={(event) => setResponsibleOperator(event.target.value)} placeholder="Name responsible for this invitation" /></label><button className="button button--ink button--small" disabled={Boolean(busy) || !inviteEmail.trim() || responsibleOperator.trim().length < 2} onClick={() => void update(`invite:${inviteEmail}`, { kind: "invite", email: inviteEmail, action: "activate", responsibleOperator }).then((updated) => { if (updated) setInviteEmail(""); })}>Activate invitation</button></div>{data.invites.length === 0 ? <Empty /> : data.invites.map((item) => { const presentation = operatorInvitePresentation(item.status); return <article key={item.id}><div><span className={`status-badge ${presentation.badgeClass}`}>{item.status}</span><strong>{item.email}</strong><p>Responsible operator: {item.adult_sponsor || "Not recorded"} · invited by {item.invited_by}</p><small>{item.last_sign_in_requested_at ? `Last sign-in requested ${formatTimestamp(new Date(item.last_sign_in_requested_at))}` : `Invited ${formatTimestamp(new Date(item.invited_at))}`}</small></div><button className={`button button--small ${item.status === "ACTIVE" ? "button--danger" : "button--outline"}`} disabled={Boolean(busy)} onClick={() => void update(`invite:${item.id}`, { kind: "invite", email: item.email, action: presentation.action, responsibleOperator: item.adult_sponsor || responsibleOperator || data.operator })}>{presentation.actionLabel}</button></article>; })}</section>
    <section className="panel operator-section"><h2>Beta feedback</h2>{data.feedback.length === 0 ? <Empty /> : data.feedback.map((item) => <article key={item.id}><div><span className="status-badge status-badge--neutral">{item.category}</span><strong>{item.public_id} · {item.page_path}</strong><p>{item.message}</p><small>{item.email || "Anonymous"} · {formatTimestamp(new Date(item.created_at))}</small></div><select aria-label={`Status for ${item.public_id}`} value={item.status} disabled={busy === `feedback:${item.id}`} onChange={(event) => void update(`feedback:${item.id}`, { kind: "feedback", id: item.id, status: event.target.value })}><option>NEW</option><option>REVIEWING</option><option>RESOLVED</option><option>CLOSED</option></select></article>)}</section>
    <section className="panel operator-section"><h2>Privacy requests</h2>{data.privacy.length === 0 ? <Empty /> : data.privacy.map((item) => {
      const draft = privacyDrafts[item.id] ?? { status: item.status, assignedTo: "", internalNotes: "", responseSummary: "", responseSent: Boolean(item.response_sent_at) };
      const identityVerified = Boolean(item.identity_verified_at);
      const correction = correctionDrafts[item.id] ?? { recordId: item.matchedRecords[0]?.id ?? "", fieldName: "project_name" as const, correctedValue: "", reason: "" };
      const anyHold = Boolean(item.activeHolds?.length);
      return <article className="operator-work-item" key={item.id}><div className="operator-request-summary"><strong>{item.request_type} · {item.public_id}</strong><p><b>Requester:</b> {item.email}</p><p>{item.details || "No requester details supplied."}</p><small>{formatTimestamp(new Date(item.created_at))}</small><div className="operator-record-matches"><b>{item.matchedRecords.length} matched retained record{item.matchedRecords.length === 1 ? "" : "s"}</b>{item.matchedRecords.map((record) => <span key={record.id}>{record.public_id} · {record.project_name} · {record.status}{record.legal_hold ? " · HOLD" : ""}{record.privacy_deletion_requested_at ? " · DELETION SCHEDULED" : ""}</span>)}</div>{item.activeHolds?.map((hold) => <div className="operator-hold" key={hold.id}><b>Hold matter</b><span>{hold.reason} · owner {hold.owner_email} · review {formatTimestamp(new Date(hold.review_at))}</span></div>)}</div><div className="operator-controls">
        <label>Status<select value={draft.status} onChange={(event) => setPrivacyDrafts((current) => ({ ...current, [item.id]: { ...draft, status: event.target.value } }))}><option>RECEIVED</option><option>VERIFYING</option><option>PROCESSING</option><option>COMPLETED</option><option>DENIED</option></select></label>
        <label>Owner<input value={draft.assignedTo} onChange={(event) => setPrivacyDrafts((current) => ({ ...current, [item.id]: { ...draft, assignedTo: event.target.value } }))} /></label>
        <p className={identityVerified ? "form-message" : "form-message is-error"}>{identityVerified ? "Identity verified through the requester’s email authentication." : "Identity not verified. Exports, corrections, holds, and deletion remain locked until the requester opens the emailed verification link."}</p>
        <label>Internal notes<textarea value={draft.internalNotes} onChange={(event) => setPrivacyDrafts((current) => ({ ...current, [item.id]: { ...draft, internalNotes: event.target.value } }))} /></label>
        <label>Final response summary<textarea value={draft.responseSummary} onChange={(event) => setPrivacyDrafts((current) => ({ ...current, [item.id]: { ...draft, responseSummary: event.target.value } }))} /></label>
        <label className="operator-checkbox"><input type="checkbox" checked={draft.responseSent} onChange={(event) => setPrivacyDrafts((current) => ({ ...current, [item.id]: { ...draft, responseSent: event.target.checked } }))} /><span>Final response sent to requester</span></label>
        <div className="operator-inline-actions"><button className="button button--ink button--small" disabled={busy === `privacy:${item.id}`} onClick={() => void update(`privacy:${item.id}`, { kind: "privacy", id: item.id, ...draft })}>Save request</button>{identityVerified ? <a className="button button--outline button--small" href={`/api/admin/privacy-export/${encodeURIComponent(item.id)}`}>Export verified data</a> : <button className="button button--outline button--small" type="button" disabled title="Verify the requester before exporting account data.">Export verified data</button>}</div>
        <div className="operator-inline-actions"><button className="button button--outline button--small" disabled={!identityVerified || item.matchedRecords.length === 0 || Boolean(busy)} onClick={() => void update(`hold:${item.id}`, { kind: "privacy_hold", id: item.id, enabled: !anyHold })}>{anyHold ? "Release legal hold" : "Apply legal hold"}</button><button className="button button--outline button--small" disabled={!identityVerified || Boolean(busy)} onClick={() => { if (window.confirm("Delete the requester's account-owned records and ancillary account data unless a legal hold applies? Reviewer-only transaction records will remain for an explicit retain/deny decision.")) void update(`delete:${item.id}`, { kind: "privacy_deletion", id: item.id }); }}>Schedule lawful deletion</button></div>
        {item.matchedRecords.length > 0 && <fieldset className="operator-correction"><legend>Append-only correction</legend><label>Record<select value={correction.recordId} onChange={(event) => setCorrectionDrafts((current) => ({ ...current, [item.id]: { ...correction, recordId: event.target.value } }))}>{item.matchedRecords.map((record) => <option key={record.id} value={record.id}>{record.public_id} · {record.project_name}</option>)}</select></label><label>Field<select value={correction.fieldName} onChange={(event) => setCorrectionDrafts((current) => ({ ...current, [item.id]: { ...correction, fieldName: event.target.value as typeof correction.fieldName } }))}><option value="agency_name">Agency name</option><option value="client_name">Client name</option><option value="project_name">Project name</option><option value="milestone_title">Milestone title</option></select></label><label>Corrected value<input value={correction.correctedValue} onChange={(event) => setCorrectionDrafts((current) => ({ ...current, [item.id]: { ...correction, correctedValue: event.target.value } }))} /></label><label>Reason<textarea value={correction.reason} onChange={(event) => setCorrectionDrafts((current) => ({ ...current, [item.id]: { ...correction, reason: event.target.value } }))} /></label><button className="button button--outline button--small" disabled={!identityVerified || !correction.correctedValue.trim() || !correction.reason.trim() || Boolean(busy)} onClick={() => void update(`correction:${item.id}`, { kind: "privacy_correction", id: item.id, ...correction })}>Record correction</button></fieldset>}
      </div></article>;
    })}</section>
    <section className="panel operator-section"><h2>Invoice job issues</h2>{data.invoiceJobs.length === 0 ? <Empty /> : data.invoiceJobs.map((item) => <article key={item.id}><AlertTriangle size={15} /><div><strong>{item.status} · record {item.record_id.slice(0, 8)}…</strong><p>{item.last_error || "Stripe invoice processing has remained active longer than expected."}</p><small>{item.attempts} attempt{item.attempts === 1 ? "" : "s"} · updated {formatTimestamp(new Date(item.updated_at))}</small></div>{item.status === "FAILED" && <button className="button button--ink button--small" disabled={Boolean(busy)} onClick={() => void update(`invoice:${item.id}`, { kind: "invoice_job", id: item.id, action: "retry" })}>Retry invoice</button>}</article>)}</section>
    <section className="panel operator-section"><h2>Verification job issues</h2>{data.jobs.length === 0 ? <Empty /> : data.jobs.map((item) => <article key={item.id}><AlertTriangle size={15} /><div><strong>{item.status} · {item.build_label}</strong><p>{item.last_error || `${item.target_origin} has remained active longer than expected.`}</p><small>{item.acknowledged_at ? `Acknowledged ${formatTimestamp(new Date(item.acknowledged_at))}` : formatTimestamp(new Date(item.created_at))}</small></div><div className="operator-inline-actions"><button className="button button--outline button--small" disabled={Boolean(busy)} onClick={() => void update(`ack:${item.id}`, { kind: "job", id: item.id, action: "acknowledge" })}>Acknowledge</button>{["QUEUED", "LEASED", "RUNNING"].includes(item.status) && <button className="button button--danger button--small" disabled={Boolean(busy)} onClick={() => { if (window.confirm("Mark this stranded job failed so it can be reviewed or retried safely?")) void update(`expire:${item.id}`, { kind: "job", id: item.id, action: "expire", reason: "Expired by operator after reviewing a stranded job." }); }}>Expire stranded job</button>}{item.status === "FAILED" && <button className="button button--ink button--small" disabled={Boolean(busy)} onClick={() => void update(`retry:${item.id}`, { kind: "job", id: item.id, action: "retry" })}>Retry safely</button>}</div></article>)}</section>
    <section className="panel operator-section"><h2>Notification delivery</h2>{data.notifications.length === 0 ? <Empty /> : data.notifications.map((item) => <article key={item.id}><AlertTriangle size={15} /><div><strong>{item.delivery_status} · {item.title}</strong><p>{item.delivery_error || `Delivery attempts: ${item.delivery_attempts ?? 0}`}</p><small>{formatTimestamp(new Date(item.created_at))}</small></div><button className="button button--outline button--small" disabled={Boolean(busy)} onClick={() => void update(`notification:${item.id}`, { kind: "notification", id: item.id, action: "retry" })}>Retry delivery</button></article>)}</section>
    <section className="panel operator-section"><h2>Failed record deletions</h2>{data.deletionFailures.length === 0 ? <Empty /> : data.deletionFailures.map((item) => <article key={item.id}><AlertTriangle size={15} /><div><strong>{item.public_id} · {item.project_name}</strong><p>{item.deletion_error || "The scheduled record purge failed."}</p><small>Requested {formatTimestamp(new Date(item.deletion_requested_at))}</small></div><button className="button button--danger button--small" disabled={Boolean(busy)} onClick={() => void update(`deletion:${item.id}`, { kind: "record_deletion", id: item.id, action: "retry" })}>Retry next maintenance run</button></article>)}</section>
    <section className="panel operator-section"><h2>Failed account deletions</h2>{data.accountDeletionFailures.length === 0 ? <Empty /> : data.accountDeletionFailures.map((item) => <article key={item.id}><AlertTriangle size={15} /><div><strong>{item.email}</strong><p>{item.last_error || "Auth account cleanup failed and will be retried by maintenance."}</p><small>{item.attempts} attempt{item.attempts === 1 ? "" : "s"} · requested {formatTimestamp(new Date(item.requested_at))}</small></div></article>)}</section>
    <section className="panel operator-section"><h2>Maintenance heartbeat</h2>{data.maintenance.length === 0 ? <p><AlertTriangle size={13} /> No maintenance heartbeat has been recorded yet.</p> : data.maintenance.map((item) => <article key={item.id}><div className={`status-badge ${item.status === "SUCCEEDED" ? "status-badge--pass" : item.status === "FAILED" ? "status-badge--fail" : "status-badge--neutral"}`}>{item.status}</div><div><strong>{item.task}</strong><p>{item.error || (item.summary ? JSON.stringify(item.summary) : "Maintenance is running.")}</p><small>{formatTimestamp(new Date(item.started_at))}{item.completed_at ? ` · completed ${formatTimestamp(new Date(item.completed_at))}` : ""}</small></div></article>)}</section>
    <OperatorList title="Operational events" items={data.events} />
  </div></main>;
}

function Empty() { return <p><CheckCircle2 size={13} /> Nothing needs attention.</p>; }
function OperatorList({ title, items }: { title: string; items: Item[] }) {
  return <section className="panel operator-section"><h2>{title}</h2>{items.length === 0 ? <Empty /> : items.map((item) => <article key={String(item.id)}><AlertTriangle size={15} /><div><strong>{String(item.event_type ?? item.status ?? item.id)}</strong><p>{typeof (item.details ?? item.title) === "string" ? String(item.details ?? item.title) : JSON.stringify(item.details ?? "Review this event")}</p><small>{formatTimestamp(new Date(item.created_at))}</small></div></article>)}</section>;
}
